### PR TITLE
Fix path separator error

### PR DESCRIPTION
**Pull request by MatchaChoco010**
When I tried to include a cross-compiled native binary of Linux on Windows, I got an error that the Output File could not be found.
The error occurred because manifestPath contained "/" as a path separator, while cargoToml.absolutePath used only "\" as a separator.
So I decided to use Path to cancel out the differences in separators between operating systems.

### CODE REVIEW

**Comment by qtdyn** [comment]
Will look at #4 and #5 when I get home in a few hours, but both look like I'll be able to merge them directly.

**Comment by qtdyn** [comment]
Tried using your modifications in the [example project](https://github.com/stardust-enterprises/gradle-rust-example) (I'm cross-compiling from Linux to i686-windows-gnu) and it seems to break a bit:
```
Building "i686-pc-windows-gnu" for target "i686-pc-windows-gnu"

Execution failed for task ':rust-library:build'.
> Didn't find the output file... report this.
  Command: cross build --message-format=json --target=i686-pc-windows-gnu --release

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':rust-library:build'.
Caused by: java.lang.RuntimeException: Didn't find the output file... report this.
Command: cross build --message-format=json --target=i686-pc-windows-gnu --release
	at fr.stardustenterprises.gradle.rust.wrapper.task.BuildTask.build(BuildTask.kt:215)
	at fr.stardustenterprises.gradle.rust.wrapper.task.BuildTask.run(BuildTask.kt:103)
```

**Comment by MatchaChoco010** [comment]
Oh, yes, it was indeed an error. My bad, my apologies.

It ran fine in my tested Windows case x86_64-pc-windows-msvc.

The reason is that the compile-artifact contents are different between x86_64-pc-windows-msvc and i686-pc-windows-gnu or x86_64-pc-windows-gnu.
In the x86_64-pc-windows-msvc case I tried, the compile-artifact appeared in the order of .dll, .dll.lib, .dll.exp and .pdb.
However, in the i686-pc-windows-gnu case, libtest.dll.a, test.d, test.dll, etc. were output.
Therefore, applying https://github.com/stardust-enterprises/gradle-rust/pull/6 was not sufficient.

My thought is that I should properly check if the file you are copying is the target dll file.
Maybe, in the case of windows, it should be written to copy the compiler-artifact of the dll extension?

**Comment by qtdyn** [comment]
~~After another test, switching from `cross` to regular `cargo`, it seems to work properly, huh.~~
Aaaaaand just before sending this comment I remembered that I **didn't** have cross installed since I reinstalled my system... alright.

The example project works now (using `cargo` instead of `cross`) even on i686-windows-gnu. (I don't see what error you were talking about and apologising for)

**Comment by xtrm-en** [comment]
Thank you for your contributions! The updated version `3.2.4` is now available on the Gradle Plugin Portal.

**Comment by qtdyn** [comment]
I currently don't have a way to test the `(i686/x86)-pc-windows-msvc` target triples on my machine since `cross` doesn't provide a Docker image for them.

**Comment by MatchaChoco010** [comment]
Oh, I am not sure what the error I saw was but I am happy if it worked.
x86-pc-windows-msvc was working in my environment.

**Comment by qtdyn** [comment]
So I just tested it in an `msvc` environment and it appears to be working as well since the `.dll` is first, so I'd consider that fixed.

**Pull request merged**
